# Generated by Django 5.0.6 on 2024-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
